services:
  heimdall:
    build:
      context: .
      dockerfile: ./build/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - LOG_LEVEL=info
      - MODEL_CONFIG_PATH=/models.yaml
      - DB_HOST=postgres
      - DB_USER=heimdall
      - DB_PORT=5432
      - DB_PASSWORD=password
      - DB_NAME=heimdall
      - DB_SSL_MODE=disable
      - DB_APPLY_MIGRATIONS=true
      - DB_MIGRATIONS_DIR=/migrations
    depends_on:
      ollama-init:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
  
  postgres:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=heimdall
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=heimdall
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U heimdall"]
      interval: 5s
      timeout: 5s
      retries: 5

  ollama:
    image: ollama/ollama:0.32.9
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    #entrypoint: ["/bin/sh", "/model_files/run_ollama.sh"]
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 5s
      timeout: 5s
      retries: 20

  ollama-init:
    image: ollama/ollama:0.32.9
    depends_on:
      ollama:
        condition: service_healthy
    environment:
      - OLLAMA_HOST=http://ollama:11434
    entrypoint: ["/bin/sh", "-c"]
    command:
      - "ollama pull qwen2.5-coder && ollama pull nomic-embed-text"

  ollama-webui:
    image: ghcr.io/ollama-webui/ollama-webui:main
    container_name: ollama-webui
    ports:
      - "3000:8080"
    volumes:
      - ollama-webui:/app/backend/data
    depends_on:
      - ollama
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  postgres-data:
  ollama: {}
  ollama-webui: {}